### ISSUE TITLE
Dataloader error

### ISSUE THREAD

**Issue by lishiyu005** [iSEE-Laboratory/EconomicGrasp#1]
Dear author,

I get errors during the training process. Is there any solution for that?

File "/home/anaconda3/envs/economic_grasp/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/anaconda3/envs/economic_grasp/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/anaconda3/envs/economic_grasp/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 312, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: unable to open shared memory object </torch_56101_3288978151> in read-write mode

Another error I have is about loading the graspness labels. The program cannot read the graspness npy file sometimes.

In addition, it takes me about 20h instead of 8h to train. I do not know the reason.

Thank you very much.

Best regards

**Comment by DravenALG** [comment]
I am sorry that I haven't seen that type of training error before. Have you trained successful once? If you can successfully train sometimes, there may be some problems in running out memory. The label loading problem may also be the memory issue and you can check the memory in your machine (using htop in linux).

About the training time, it is different in different environment. My training time is tested in an empty machine with a RTX3090. Because the data loading needs a lot of memory and CPU calculation, it will be highly affected  by how many other processes running in the same machine. 

Although the training time may be different, you can compare my training time with GSNet in the same environment, and you can see the speed up.

**Comment by lishiyu005** [comment]
Yes, I try economic grasp and it is indeed much faster than GSnet. The error may be from limited CPU memory.
